//define possible unique game states
const actionTypes = {
  "CAN_CASTLE" : "CAN_CASTLE",
  "GENERATE_CANDIDATE_MOVES" : "GENERATE_CANDIDATE_MOVES",
  "NEW_MOVE" : "NEW_MOVE",
  "CLEAR_CANDIDATE_MOVES" : "CLEAR_CANDIDATE_MOVES",
  "PROMOTION_OPEN" : "PROMOTION_OPEN",
  "PROMOTION_CLOSE" : "PROMOTION_CLOSE",
  "STALEMATE" : "STALEMATE",
  "NEW_GAME" : "NEW_GAME",
  "INSUFFICIENT_MATERIAL" : "INSUFFICIENT_MATERIAL",
  "WIN" : "WIN",
  "TAKE_BACK" : "TAKE_BACK",
  "UPDATE_STOCKFISH" : "UPDATE_STOCKFISH"
};

export default actionTypes;